// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID            uuid.UUID          `json:"id"`
	Type          string             `json:"type"`
	BinaryUrl     string             `json:"binary_url"`
	BinarySha256  string             `json:"binary_sha256"`
	Arguments     []string           `json:"arguments"`
	EnvVariables  []byte             `json:"env_variables"`
	Priority      string             `json:"priority"`
	Status        string             `json:"status"`
	ExecutorID    pgtype.Text        `json:"executor_id"`
	Stdout        pgtype.Text        `json:"stdout"`
	Stderr        pgtype.Text        `json:"stderr"`
	ExitCode      pgtype.Int4        `json:"exit_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
}

type JobAttempt struct {
	ID           uuid.UUID          `json:"id"`
	JobID        uuid.UUID          `json:"job_id"`
	ExecutorID   string             `json:"executor_id"`
	ExecutorIp   string             `json:"executor_ip"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}
