// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID            uuid.UUID        `json:"id"`
	Type          string           `json:"type"`
	BinaryUrl     string           `json:"binary_url"`
	BinarySha256  string           `json:"binary_sha256"`
	Arguments     []string         `json:"arguments"`
	EnvVariables  []byte           `json:"env_variables"`
	Priority      string           `json:"priority"`
	Status        string           `json:"status"`
	ExecutorID    *string          `json:"executor_id"`
	Stdout        *string          `json:"stdout"`
	Stderr        *string          `json:"stderr"`
	ExitCode      *int32           `json:"exit_code"`
	ErrorMessage  *string          `json:"error_message"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
	LastHeartbeat pgtype.Timestamp `json:"last_heartbeat"`
}

type JobAttempt struct {
	ID           uuid.UUID        `json:"id"`
	JobID        uuid.UUID        `json:"job_id"`
	ExecutorID   string           `json:"executor_id"`
	ExecutorIp   string           `json:"executor_ip"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	EndedAt      pgtype.Timestamp `json:"ended_at"`
	Status       string           `json:"status"`
	ErrorMessage *string          `json:"error_message"`
}
