// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelJob(ctx context.Context, id uuid.UUID) (Job, error)
	ClaimNextJob(ctx context.Context, executorID *string) (Job, error)
	CleanupOldJobs(ctx context.Context, dollar_1 pgtype.Interval) error
	CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error)
	CountJobAttempts(ctx context.Context, jobID uuid.UUID) (int64, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	DeleteJob(ctx context.Context, id uuid.UUID) error
	FailJob(ctx context.Context, arg FailJobParams) (Job, error)
	FindStaleJobs(ctx context.Context) ([]Job, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetJobAttempts(ctx context.Context, jobID uuid.UUID) ([]JobAttempt, error)
	GetLatestJobAttempt(ctx context.Context, jobID uuid.UUID) (JobAttempt, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	RecordJobAttempt(ctx context.Context, arg RecordJobAttemptParams) (JobAttempt, error)
	ResetStaleJob(ctx context.Context, id uuid.UUID) error
	UpdateHeartbeat(ctx context.Context, arg UpdateHeartbeatParams) error
	UpdateJobAttempt(ctx context.Context, arg UpdateJobAttemptParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
